### ISSUE TITLE
Too many queued stakings can cause slow block production

### ISSUE THREAD

**Issue by hallazzang** [tendermint/farming#261]
We can put ending timestamp inside store keys to mitigate this problem.
When queuing staking, the end time is set to current blocktime + `time.Duration(params.NextEpochDays)`, and queued staking will be processed at the end time, not when the epoch increases.

## Tasks
- [ ] Fix QueuedStaking logics
- [ ] Fix relevant test cases
- [ ] Add migration.go, legacy code
- [ ] bump `ConsensusVersion` of farming to 2 from 1
- [ ] Update Spec, docs, cli help
