### ISSUE TITLE
feat: Transaction Command-Line Interface

### ISSUE THREAD

**Issue by kogisin** [tendermint/farming#41]
## Summary

This feature provides one way to interact with a node. This feature builds a command-line interface for farming transactions.

## Tasks

- [x] CreateFixedAmountPlan
- [x] CreateRatioPlan
- [x] Stake
- [x] Unstake
- [x] Harvest
- [x] Write Testcode
- [x] Add detailed description and example
____

## Reference

- [Cosmos SDK Command-Line Interface Documentation](https://docs.cosmos.network/v0.39/interfaces/cli.html)

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kogisin** [comment]
I'll write the integration tests for command-line interface in the other PR due to the upcoming MVP version's deadline.
