### ISSUE TITLE
F1 distribution on farming

### ISSUE THREAD

**Issue by dongsam** [tendermint/farming#91]
## Summary

- We decided to include F1 distribution for Farming Module v1.0 #89
  - What is F1 distribution? : [paper](https://github.com/cosmos/cosmos-sdk/blob/master/docs/spec/fee_distribution/f1_fee_distr.pdf)
  - Benefits: no reward calculation burden on every end of epoch, efficient data storage
  - Impact: it will delay completion of codebase about 2~3 weeks (from September to October)

## Bullet Points

- [x] PoC
- [x] Update spec
- [x] Add and change struct, proto for f1, 
- [ ] Implementation F1 logic
- [ ] Update cli, query, tx interface
- [ ] Fix `params.EpochDays` to `params.NextEpochDays`

## References

- https://github.com/tendermint/farming/pull/89
- https://docs.cosmos.network/master/architecture/adr-039-epoched-staking.html
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
