### ISSUE TITLE
Fix params.EpochDays to params.NextEpochDays

### ISSUE THREAD

**Issue by dongsam** [tendermint/farming#96]
## Problem Definition

Currently, end-of-epoch uses `params.EpochDays` directly when allocating farming rewards. However, if `params.EpochDays` are changed by Parameter ChangeProposal in the middle of the epoch, the already started epoch will perform farming allocation based on the changed `params.EpochDays`. Therefore, even if Epoch Days is changed in the middle of the epoch, it is necessary to ensure that the changed Epoch Days can be used in the next epoch without affecting the farming reward allocation of the epoch.

## Proposal

To this end, `CurrentEpochDays`(global state) need to be added to check the current Epoch Days, and the existing `params.EpochDays` is renamed and repurposed to `params.NextEpochDays`, so if `CurrentEpochDays` and `params.NextEpochDays` are different at the start of the new epoch, then update `CurrentEpochDays` to `params.NextEpochDays`

## Tasks

- [x] Add `CurrentEpochDays` or `EpochEra`
- [x] Rename and fix logics for `params.EpochDays` to `params.NextEpochDays`
- [x] Update spec and description

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kogisin** [comment]
Ref: https://github.com/tendermint/farming/pull/89
